use_frameworks!

platform :ios, '8.0'

target 'AMKBundleSettingsManager_Example' do
  pod 'AMKBundleSettingsManager', :path => '../'

  target 'AMKBundleSettingsManager_Tests' do
    inherit! :search_paths

    
  end
end
